# Generated by Django 5.0.3 on 2024-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
