# Generated by Django 5.0.3 on 2024-03-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-publish_date"], "verbose_name_plural": "news"},
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "redactor", "verbose_name_plural": "redactors"},
        ),
        migrations.RenameField(
            model_name="news",
            old_name="topic",
            new_name="topics",
        ),
    ]
