# Generated by Django 5.0.3 on 2024-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0004_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
